<?php

/**
 * Implements hook_entity_info().
 */
function civicrmentity_entity_info() {
  $info = array();
  if (!civicrm_initialize()) {
    return;
  }
  require_once 'api/api.php';
  $entities = civicrm_api('Entity', 'Get', array('version' => 3));
  foreach ($entities['values'] as $value) {

    // Remove camel case for entity type.
    $entity_type = $value;
    $entity_type[0] = strtolower($entity_type[0]);
    $func = create_function('$c', 'return "_" . strtolower($c[1]);');
    $entity_type = preg_replace_callback('/([A-Z])/', $func, $entity_type);

    // Remove camel case for label.
    $func = create_function('$c', 'return " " . $c[1];');
    $label = preg_replace_callback('/([A-Z])/', $func, $value);

    $key = 'civicrm_'. $entity_type;

    $info[$key] = array(
      'label' => $label,
      'controller class' => 'CiviCRMEntityController',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'id',
      ),
      'bundles' => array(
        $key => array(
          'label' => $label,
          'admin' => array(
            'path' => 'admin/config/civicrm/entity/'. str_replace('_', '-', $entity_type),
          ),
        ),
      ),

      // Existence of this property indicates that this is a CiviCRM entity to other
      // parts of this module.
      'civicrm' => array(
        'entity' => $value,
      ),
      'static cache' => FALSE,
    );
  }
  return $info;
}

/**
 * Implements hook_menu().
 */
function civicrmentity_menu() {
  $items = array();
  $items['admin/config/civicrm/entity'] = array(
    'title' => 'Entity',
    'description' => 'Fieldable CiviCRM entities',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function civicrmentity_menu_alter(&$items) {
  foreach (entity_get_info() as $entity_info) {
    if (isset($entity_info['civicrm'])) {
      foreach ($entity_info['bundles'] as $file_type => $bundle_info) {
        if (isset($bundle_info['admin'])) {

          // Get the base path and access.
          $path = $bundle_info['admin']['path'];
          $items[$path] = $items[$path .'/fields'];
          $items[$path]['type'] = MENU_NORMAL_ITEM;
          $items[$path]['title'] = $entity_info['label'];
          $items[$path]['description'] = t('CiviCRM @entity entity', array('@entity' => $entity_info['civicrm']['entity']));
          $items[$path .'/fields']['type'] = MENU_DEFAULT_LOCAL_TASK;
        }
      }
    }
  }
}
